/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  AIDetector: () => AIDetector,
  default: () => CSCPlugin,
  detectPhraseErrors: () => detectPhraseErrors,
  findPhraseMatches: () => findPhraseMatches,
  locateUniqueOriginal: () => locateUniqueOriginal,
  parsePhraseDictionary: () => parsePhraseDictionary,
  toDetectionResult: () => toDetectionResult,
  validateAIResult: () => validateAIResult,
  addParagraphOffsets: () => addParagraphOffsets,
  applyChangesToOffsets: () => applyChangesToOffsets,
  locateParagraph: () => locateParagraph,
  splitParagraphs: () => splitParagraphs
});
module.exports = __toCommonJS(main_exports);
var import_obsidian5 = require("obsidian");

// src/settings.ts
var import_obsidian = require("obsidian");

// src/types.ts
var CATEGORY_LABELS = {
  typo: "错别字",
  punctuation: "标点",
  grammar: "语法"
};
var MODE_LABELS = {
  quick: "快速模式",
  standard: "标准模式",
  deep: "深度模式"
};
var MODE_DESCRIPTIONS = {
  quick: "仅检测错别字（音近字、形近字、笔误）",
  standard: "检测错别字 + 标点符号 + 语法错误",
  deep: "全部检测 + 表达优化建议"
};
var LICENSE_LABELS = {
  basic: "基础版",
  full: "正式版"
};
var LICENSE_DESCRIPTIONS = {
  basic: "快速模式检测，适合日常简单校对",
  full: "全部检测模式，包含标点、语法、表达优化"
};
var DEFAULT_SETTINGS = {
  apiKey: "",
  apiEndpoint: "https://api.deepseek.com/v1/chat/completions",
  modelName: "deepseek-chat",
  ignoredWords: [],
  phraseDictionary: [],
  maxSegmentLength: 1500,
  timeout: 3e4,
  detectionMode: "quick",
  licenseType: "full",
  activationCode: "",
  activatedAt: ""
};

// src/services/ActivationService.ts
var LOCAL_STORAGE_KEY = "csc_license";
var API_ENDPOINT = "https://kbfwajzlaswbqesgxedu.supabase.co/rest/v1/activation_codes_proofreader";
var API_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtiZndhanpsYXN3YnFlc2d4ZWR1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwMjU5MjYsImV4cCI6MjA2MjYwMTkyNn0.RyoKxCOwAzGnwD2B1mjm2s9IOb1btKcrN94jf2RtPbQ";
var ActivationService = class {
  static isFullVersion(licenseType) {
    return licenseType === "full";
  }
  static isBasicVersion(licenseType) {
    return licenseType === "basic";
  }
  checkLocalLicenseStatus() {
    try {
      const storedLicense = localStorage.getItem(LOCAL_STORAGE_KEY);
      if (storedLicense) {
        const licenseInfo = JSON.parse(storedLicense);
        if (licenseInfo.licenseType) {
          return licenseInfo.licenseType;
        }
      }
    } catch (error) {
    }
    return "full";
  }
  getLocalLicenseInfo() {
    try {
      const storedLicense = localStorage.getItem(LOCAL_STORAGE_KEY);
      if (storedLicense) {
        return JSON.parse(storedLicense);
      }
    } catch (error) {
    }
    return null;
  }
  saveLicenseToLocalStorage(licenseInfo) {
    try {
      localStorage.setItem(LOCAL_STORAGE_KEY, JSON.stringify(licenseInfo));
    } catch (error) {
    }
  }
  clearLicenseFromLocalStorage() {
    try {
      localStorage.removeItem(LOCAL_STORAGE_KEY);
    } catch (error) {
    }
  }
  async activate(activationCode) {
    if (!activationCode || activationCode.trim().length === 0) {
      return {
        success: false,
        message: "请输入激活码"
      };
    }
    const trimmedCode = activationCode.trim();
    try {
      const url = `${API_ENDPOINT}?code=eq.${encodeURIComponent(trimmedCode)}&select=*`;
      const response = await fetch(url, {
        method: "GET",
        headers: {
          "apikey": API_KEY,
          "Authorization": `Bearer ${API_KEY}`,
          "Content-Type": "application/json"
        }
      });
      if (!response.ok) {
        const errorText = await response.text();
        return {
          success: false,
          message: `服务器错误: HTTP ${response.status}`
        };
      }
      const data = await response.json();
      if (!data || data.length === 0) {
        return {
          success: false,
          message: "激活码无效，请检查后重试"
        };
      }
      const codeRecord = data[0];
      if (codeRecord.status === "used") {
        return {
          success: false,
          message: "该激活码已被使用"
        };
      }
      const updateUrl = `${API_ENDPOINT}?code=eq.${encodeURIComponent(trimmedCode)}`;
      const updateResponse = await fetch(updateUrl, {
        method: "PATCH",
        headers: {
          "apikey": API_KEY,
          "Authorization": `Bearer ${API_KEY}`,
          "Content-Type": "application/json",
          "Prefer": "return=minimal"
        },
        body: JSON.stringify({
          status: "used",
          used_at: (/* @__PURE__ */ new Date()).toISOString()
        })
      });
      if (!updateResponse.ok) {
        return {
          success: false,
          message: "激活失败，请稍后重试"
        };
      }
      const licenseInfo = {
        licenseType: "full",
        activationCode: trimmedCode,
        activatedAt: (/* @__PURE__ */ new Date()).toISOString()
      };
      this.saveLicenseToLocalStorage(licenseInfo);
      return {
        success: true,
        message: "激活成功！已升级为正式版",
        licenseType: "full"
      };
    } catch (error) {
      if (error instanceof Error) {
        if (error.message.includes("fetch")) {
          return {
            success: false,
            message: "网络连接失败，请检查网络后重试"
          };
        }
        return {
          success: false,
          message: `激活失败: ${error.message}`
        };
      }
      return {
        success: false,
        message: "激活失败，请稍后重试"
      };
    }
  }
  deactivate() {
    this.clearLicenseFromLocalStorage();
  }
  isValidActivationCode(code) {
    if (!code || typeof code !== "string") {
      return false;
    }
    const trimmed = code.trim();
    return trimmed.length >= 8 && trimmed.length <= 64;
  }
};
var activationService = new ActivationService();

// src/settings.ts
var CSCSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.testButton = null;
    this.testStatus = null;
    this.activationStatus = null;
    this.activationButton = null;
    this.modeDropdown = null;
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "中文校对设置" });
    this.renderLicenseSection(containerEl);
    this.renderApiSettings(containerEl);
    this.renderEngineSettings(containerEl);
    this.renderIgnoredWordsSettings(containerEl);
    this.renderPhraseDictionarySettings(containerEl);
    this.renderAdvancedSettings(containerEl);
  }
  renderLicenseSection(containerEl) {
    containerEl.createEl("h3", { text: "许可证" });
    const licenseType = "full";
    const isFullVersion = true;
    const statusContainer = containerEl.createDiv({ cls: "csc-license-status-container" });
    this.activationStatus = statusContainer.createDiv({ cls: "csc-license-status" });
    this.renderLicenseStatus(this.activationStatus, licenseType);
  }
  renderLicenseStatus(container, licenseType) {
    container.empty();
    const isFullVersion = ActivationService.isFullVersion(licenseType);
    const statusClass = isFullVersion ? "csc-license-full" : "csc-license-basic";
    const statusText = isFullVersion ? "✓ 正式版" : "基础版";
    container.createEl("span", {
      cls: `csc-license-badge ${statusClass}`,
      text: statusText
    });
    container.createEl("span", {
      cls: "csc-license-desc",
      text: LICENSE_DESCRIPTIONS[licenseType]
    });
  }
  renderFeatureComparison(container) {
    container.createEl("div", { cls: "csc-feature-comparison-title", text: "版本功能对比" });
    const table = container.createEl("table", { cls: "csc-feature-table" });
    const thead = table.createEl("thead");
    const headerRow = thead.createEl("tr");
    headerRow.createEl("th", { text: "功能" });
    headerRow.createEl("th", { text: "基础版" });
    headerRow.createEl("th", { text: "正式版" });
    const tbody = table.createEl("tbody");
    const features = [
      { name: "错别字检测", basic: "✓", full: "✓" },
      { name: "标点符号检查", basic: "-", full: "✓" },
      { name: "语法错误检测", basic: "-", full: "✓" },
      { name: "表达优化建议", basic: "-", full: "✓" },
      { name: "编辑器高亮", basic: "✓", full: "✓" },
      { name: "上下文预览", basic: "✓", full: "✓" }
    ];
    for (const feature of features) {
      const row = tbody.createEl("tr");
      row.createEl("td", { text: feature.name });
      row.createEl("td", {
        text: feature.basic,
        cls: feature.basic === "✓" ? "csc-feature-available" : "csc-feature-unavailable"
      });
      row.createEl("td", {
        text: feature.full,
        cls: feature.full === "✓" ? "csc-feature-available" : "csc-feature-unavailable"
      });
    }
  }
  async handleActivation() {
    const activationCode = this.plugin.settings.activationCode;
    if (!activationCode || activationCode.trim().length === 0) {
      new import_obsidian.Notice("请输入激活码");
      return;
    }
    if (this.activationButton) {
      this.activationButton.setAttribute("disabled", "true");
      this.activationButton.textContent = "激活中...";
    }
    try {
      const result = await activationService.activate(activationCode);
      if (result.success) {
        this.plugin.settings.licenseType = result.licenseType || "full";
        this.plugin.settings.activatedAt = (/* @__PURE__ */ new Date()).toISOString();
        await this.plugin.saveSettings();
        new import_obsidian.Notice(result.message);
        this.display();
      } else {
        new import_obsidian.Notice(result.message);
        if (this.activationButton) {
          this.activationButton.removeAttribute("disabled");
          this.activationButton.textContent = "激活";
        }
      }
    } catch (error) {
      console.error("Activation error:", error);
      new import_obsidian.Notice("激活失败，请稍后重试");
      if (this.activationButton) {
        this.activationButton.removeAttribute("disabled");
        this.activationButton.textContent = "激活";
      }
    }
  }
  renderApiSettings(containerEl) {
    containerEl.createEl("h3", { text: "API 配置" });
    new import_obsidian.Setting(containerEl).setName("API Key").setDesc("输入你的 AI 服务 API Key（支持 DeepSeek、OpenAI 兼容接口）").addText(
      (text) => text.setPlaceholder("sk-...").setValue(this.plugin.settings.apiKey).onChange(async (value) => {
        this.plugin.settings.apiKey = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("API 端点").setDesc("AI 服务的 API 端点地址").addText(
      (text) => text.setPlaceholder("https://api.deepseek.com/v1/chat/completions").setValue(this.plugin.settings.apiEndpoint).onChange(async (value) => {
        this.plugin.settings.apiEndpoint = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("模型名称").setDesc("使用的模型名称").addText(
      (text) => text.setPlaceholder("deepseek-chat").setValue(this.plugin.settings.modelName).onChange(async (value) => {
        this.plugin.settings.modelName = value;
        await this.plugin.saveSettings();
      })
    );
    const testSetting = new import_obsidian.Setting(containerEl).setName("测试连接").setDesc("测试 API 配置是否正确");
    this.testStatus = testSetting.controlEl.createDiv({ cls: "csc-test-status" });
    testSetting.addButton((btn) => {
      btn.setButtonText("测试连接");
      btn.setClass("csc-test-btn");
      btn.onClick(async () => {
        await this.testConnection(btn);
      });
      this.testButton = btn.buttonEl;
    });
  }
  async testConnection(btn) {
    var _a;
    const { apiKey, apiEndpoint, modelName, timeout } = this.plugin.settings;
    if (!apiKey) {
      this.updateTestStatus("error", "请先输入 API Key");
      return;
    }
    if (!apiEndpoint) {
      this.updateTestStatus("error", "请先输入 API 端点");
      return;
    }
    btn.setDisabled(true);
    btn.setButtonText("测试中...");
    this.updateTestStatus("testing", "正在测试连接...");
    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), timeout);
    try {
      const response = await fetch(apiEndpoint, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "Authorization": `Bearer ${apiKey}`
        },
        body: JSON.stringify({
          model: modelName,
          messages: [
            {
              role: "user",
              content: "你好"
            }
          ],
          max_tokens: 10
        }),
        signal: controller.signal
      });
      clearTimeout(timeoutId);
      if (!response.ok) {
        const errorText = await response.text();
        let errorMsg = `HTTP ${response.status}`;
        try {
          const errorJson = JSON.parse(errorText);
          if ((_a = errorJson.error) == null ? void 0 : _a.message) {
            errorMsg = errorJson.error.message;
          }
        } catch (e) {
        }
        this.updateTestStatus("error", `连接失败: ${errorMsg}`);
        return;
      }
      const data = await response.json();
      if (data.choices && data.choices.length > 0) {
        this.updateTestStatus("success", "连接成功！API 配置正确");
        new import_obsidian.Notice("API 连接测试成功");
      } else {
        this.updateTestStatus("error", "响应格式异常，请检查模型名称");
      }
    } catch (error) {
      clearTimeout(timeoutId);
      if (error instanceof Error) {
        if (error.name === "AbortError") {
          this.updateTestStatus("error", "连接超时，请检查网络或增加超时时间");
        } else {
          this.updateTestStatus("error", `连接失败: ${error.message}`);
        }
      } else {
        this.updateTestStatus("error", "连接失败: 未知错误");
      }
    } finally {
      btn.setDisabled(false);
      btn.setButtonText("测试连接");
    }
  }
  updateTestStatus(status, message) {
    if (!this.testStatus)
      return;
    this.testStatus.empty();
    this.testStatus.className = "csc-test-status";
    this.testStatus.createSpan({
      cls: `csc-test-status-${status}`,
      text: message
    });
  }
  renderEngineSettings(containerEl) {
    containerEl.createEl("h3", { text: "检测配置" });
    const isFullVersion = ActivationService.isFullVersion(this.plugin.settings.licenseType);
    const modeSetting = new import_obsidian.Setting(containerEl).setName("检测模式").setDesc("选择校对的检测范围和深度").addDropdown((dropdown) => {
      this.modeDropdown = dropdown;
      dropdown.addOption("quick", MODE_LABELS.quick);
      dropdown.addOption("standard", MODE_LABELS.standard);
      dropdown.addOption("deep", MODE_LABELS.deep);
      dropdown.setValue(this.plugin.settings.detectionMode).onChange(async (value) => {
        this.plugin.settings.detectionMode = value;
        await this.plugin.saveSettings();
        this.updateModeDescription(containerEl, value);
      });
    });
    const modeDescEl = containerEl.createDiv({ cls: "csc-mode-desc" });
    this.renderModeDescription(modeDescEl, this.plugin.settings.detectionMode);
  }
  renderModeDescription(container, mode) {
    container.empty();
    const desc = MODE_DESCRIPTIONS[mode];
    container.createEl("div", { cls: "csc-mode-desc-content", text: desc });
    const features = container.createEl("div", { cls: "csc-mode-features" });
    switch (mode) {
      case "quick":
        features.createEl("span", { cls: "csc-mode-tag csc-mode-tag-typo", text: "错别字" });
        break;
      case "standard":
        features.createEl("span", { cls: "csc-mode-tag csc-mode-tag-typo", text: "错别字" });
        features.createEl("span", { cls: "csc-mode-tag csc-mode-tag-punctuation", text: "标点" });
        features.createEl("span", { cls: "csc-mode-tag csc-mode-tag-grammar", text: "语法" });
        break;
      case "deep":
        features.createEl("span", { cls: "csc-mode-tag csc-mode-tag-typo", text: "错别字" });
        features.createEl("span", { cls: "csc-mode-tag csc-mode-tag-punctuation", text: "标点" });
        features.createEl("span", { cls: "csc-mode-tag csc-mode-tag-grammar", text: "语法" });
        features.createEl("span", { cls: "csc-mode-tag csc-mode-tag-expression", text: "表达优化" });
        break;
    }
  }
  updateModeDescription(containerEl, mode) {
    const existingDesc = containerEl.querySelector(".csc-mode-desc");
    if (existingDesc) {
      this.renderModeDescription(existingDesc, mode);
    }
  }
  renderIgnoredWordsSettings(containerEl) {
    containerEl.createEl("h3", { text: "忽略词库" });
    new import_obsidian.Setting(containerEl).setName("忽略词列表").setDesc("这些词将不会被检测为错别字（每行一个词）").addTextArea(
      (text) => text.setPlaceholder("输入要忽略的词汇...").setValue(this.plugin.settings.ignoredWords.join("\n")).onChange(async (value) => {
        this.plugin.settings.ignoredWords = value.split("\n").map((word) => word.trim()).filter((word) => word.length > 0);
        await this.plugin.saveSettings();
      })
    );
  }
  renderPhraseDictionarySettings(containerEl) {
    containerEl.createEl("h3", { text: "固定词组校对词典" });
    new import_obsidian.Setting(containerEl).setName("自定义固定词组").setDesc("每行一项，格式：错误词 => 正确词。相同错误词会覆盖内置词典。").addTextArea(
      (text) => text.setPlaceholder("例如：迫不急待 => 迫不及待").setValue(this.plugin.settings.phraseDictionary.join("\n")).onChange(async (value) => {
        this.plugin.settings.phraseDictionary = value.split("\n").map((line) => line.trim()).filter((line) => line.length > 0);
        await this.plugin.saveSettings();
      })
    );
  }
  renderAdvancedSettings(containerEl) {
    containerEl.createEl("h3", { text: "高级设置" });
    new import_obsidian.Setting(containerEl).setName("分段长度").setDesc("AI 检测时每段文本的最大字符数（建议 1000-2000）").addSlider(
      (slider) => slider.setLimits(500, 3e3, 100).setValue(this.plugin.settings.maxSegmentLength).setDynamicTooltip().onChange(async (value) => {
        this.plugin.settings.maxSegmentLength = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("请求超时").setDesc("API 请求超时时间（毫秒）").addText(
      (text) => text.setValue(String(this.plugin.settings.timeout)).onChange(async (value) => {
        const timeout = parseInt(value, 10);
        if (!isNaN(timeout) && timeout > 0) {
          this.plugin.settings.timeout = timeout;
          await this.plugin.saveSettings();
        }
      })
    );
  }
};

// src/view.ts
var import_obsidian2 = require("obsidian");
var VIEW_TYPE_CSC = "csc-view";
var CSCView = class extends import_obsidian2.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.results = [];
    this.filteredResults = [];
    this.activeFilter = "all";
    this.status = "idle";
    this.errorMessage = "";
    this.containerDiv = null;
    this.originalText = "";
    this.plugin = plugin;
  }
  getViewType() {
    return VIEW_TYPE_CSC;
  }
  getDisplayText() {
    return "中文校对";
  }
  getIcon() {
    return "spell-check";
  }
  async onOpen() {
    this.render();
  }
  async onClose() {
  }
  setResults(results, originalText) {
    this.results = results;
    if (originalText !== void 0) {
      this.originalText = originalText;
    }
    this.applyFilter();
    this.render();
  }
  setOriginalText(text) {
    this.originalText = text;
  }
  setStatus(status, errorMessage) {
    this.status = status;
    this.errorMessage = errorMessage || "";
    this.render();
  }
  applyFilter() {
    if (this.activeFilter === "all") {
      this.filteredResults = [...this.results];
    } else {
      this.filteredResults = this.results.filter((r) => r.category === this.activeFilter);
    }
  }
  getCategoryCount(category) {
    if (category === "all")
      return this.results.length;
    return this.results.filter((r) => r.category === category).length;
  }
  getActiveCategories() {
    const categories = /* @__PURE__ */ new Set();
    this.results.forEach((r) => categories.add(r.category));
    return Array.from(categories);
  }
  extractContext(offset, length, contextLength = 20) {
    if (!this.originalText)
      return null;
    const beforeStart = Math.max(0, offset - contextLength);
    const before = this.originalText.slice(beforeStart, offset);
    const error = this.originalText.slice(offset, offset + length);
    const afterEnd = Math.min(this.originalText.length, offset + length + contextLength);
    const after = this.originalText.slice(offset + length, afterEnd);
    return { before, error, after };
  }
  render() {
    const container = this.containerEl.children[1];
    container.empty();
    container.createEl("div", { cls: "csc-container" }, (div) => {
      this.containerDiv = div;
      this.renderHeader(div);
      this.renderFilterBar(div);
      this.renderContent(div);
      this.renderFooter(div);
    });
  }
  renderHeader(container) {
    container.createEl("div", { cls: "csc-header" }, (header) => {
      header.createEl("div", { cls: "csc-header-top" }, (top) => {
        top.createEl("div", { cls: "csc-title-row" }, (titleRow) => {
          const iconEl = titleRow.createEl("div", { cls: "csc-title-icon" });
          (0, import_obsidian2.setIcon)(iconEl, "spell-check");
          titleRow.createEl("h3", { text: "中文校对", cls: "csc-title" });
        });
        const statusEl = top.createEl("div", { cls: "csc-status" });
        this.renderStatus(statusEl);
      });
      const isFullVersion = this.plugin.isFullVersion();
      const licenseLabel = LICENSE_LABELS[this.plugin.settings.licenseType];
      const licenseClass = isFullVersion ? "csc-license-full" : "csc-license-basic";
      header.createEl("div", { cls: `csc-license-indicator ${licenseClass}` }, (indicator) => {
        indicator.createEl("span", { text: licenseLabel });
      });
      const modeLabel = MODE_LABELS[this.plugin.settings.detectionMode] || "快速模式";
      header.createEl("div", { cls: "csc-mode-indicator", text: modeLabel });
      header.createEl("button", {
        cls: "csc-detect-btn"
      }, (btn) => {
        if (this.status === "detecting") {
          btn.createEl("div", { cls: "csc-btn-spinner" });
          btn.createEl("span", { text: "检测中..." });
          btn.disabled = true;
        } else {
          (0, import_obsidian2.setIcon)(btn.createEl("div", { cls: "csc-btn-icon" }), "search");
          btn.createEl("span", { text: "开始检测" });
        }
        btn.addEventListener("click", () => {
          this.startDetection();
        });
      });
    });
  }
  renderFilterBar(container) {
    if (this.results.length === 0 || this.status !== "completed")
      return;
    container.createEl("div", { cls: "csc-filter-bar" }, (bar) => {
      bar.createEl("button", {
        cls: `csc-filter-btn ${this.activeFilter === "all" ? "csc-filter-active" : ""}`,
        text: `全部 (${this.getCategoryCount("all")})`
      }, (btn) => {
        btn.addEventListener("click", () => {
          this.activeFilter = "all";
          this.applyFilter();
          this.render();
        });
      });
      const activeCategories = this.getActiveCategories();
      for (const cat of activeCategories) {
        const count = this.getCategoryCount(cat);
        bar.createEl("button", {
          cls: `csc-filter-btn csc-filter-${cat} ${this.activeFilter === cat ? "csc-filter-active" : ""}`,
          text: `${CATEGORY_LABELS[cat]} (${count})`
        }, (btn) => {
          btn.addEventListener("click", () => {
            this.activeFilter = cat;
            this.applyFilter();
            this.render();
          });
        });
      }
    });
  }
  renderStatus(container) {
    switch (this.status) {
      case "idle":
        container.createEl("span", {
          text: "准备就绪",
          cls: "csc-status-badge csc-status-idle"
        });
        break;
      case "detecting":
        container.createEl("span", {
          text: "检测中",
          cls: "csc-status-badge csc-status-detecting"
        });
        break;
      case "completed":
        const count = this.results.length;
        if (count === 0) {
          container.createEl("span", {
            text: "未发现问题",
            cls: "csc-status-badge csc-status-success"
          });
        } else {
          container.createEl("span", {
            text: `发现 ${count} 处问题`,
            cls: "csc-status-badge csc-status-warning"
          });
        }
        break;
      case "error":
        container.createEl("span", {
          text: "检测失败",
          cls: "csc-status-badge csc-status-error"
        });
        break;
    }
  }
  renderContent(container) {
    container.createEl("div", { cls: "csc-content" }, (content) => {
      if (this.status === "detecting") {
        this.renderLoading(content);
        return;
      }
      if (this.status === "error") {
        this.renderError(content);
        return;
      }
      if (this.results.length === 0 && this.status === "completed") {
        this.renderSuccess(content);
        return;
      }
      if (this.results.length === 0) {
        this.renderEmpty(content);
        return;
      }
      if (this.filteredResults.length === 0) {
        this.renderFilterEmpty(content);
        return;
      }
      this.renderResults(content);
    });
  }
  renderLoading(container) {
    container.createEl("div", { cls: "csc-loading" }, (loading) => {
      loading.createEl("div", { cls: "csc-loading-animation" }, (anim) => {
        for (let i = 0; i < 3; i++) {
          anim.createEl("div", { cls: "csc-loading-dot" });
        }
      });
      loading.createEl("div", { cls: "csc-loading-text" }, (text) => {
        text.createEl("span", { text: "AI 正在分析文本..." });
        text.createEl("span", { text: "请稍候", cls: "csc-loading-sub" });
      });
    });
  }
  renderError(container) {
    container.createEl("div", { cls: "csc-message csc-message-error" }, (msg) => {
      const iconEl = msg.createEl("div", { cls: "csc-message-icon" });
      (0, import_obsidian2.setIcon)(iconEl, "alert-circle");
      msg.createEl("div", { cls: "csc-message-content" }, (content) => {
        content.createEl("div", { text: "检测失败", cls: "csc-message-title" });
        content.createEl("div", { text: this.errorMessage || "请检查 API 配置后重试", cls: "csc-message-desc" });
      });
    });
  }
  renderSuccess(container) {
    container.createEl("div", { cls: "csc-message csc-message-success" }, (msg) => {
      const iconEl = msg.createEl("div", { cls: "csc-message-icon" });
      (0, import_obsidian2.setIcon)(iconEl, "check-circle");
      msg.createEl("div", { cls: "csc-message-content" }, (content) => {
        content.createEl("div", { text: "太棒了！", cls: "csc-message-title" });
        content.createEl("div", { text: "没有发现问题", cls: "csc-message-desc" });
      });
    });
  }
  renderEmpty(container) {
    container.createEl("div", { cls: "csc-message csc-message-empty" }, (msg) => {
      const iconEl = msg.createEl("div", { cls: "csc-message-icon" });
      (0, import_obsidian2.setIcon)(iconEl, "file-text");
      msg.createEl("div", { cls: "csc-message-content" }, (content) => {
        content.createEl("div", { text: "准备检测", cls: "csc-message-title" });
        content.createEl("div", { text: "点击上方按钮开始检测当前文档", cls: "csc-message-desc" });
      });
    });
  }
  renderFilterEmpty(container) {
    container.createEl("div", { cls: "csc-message csc-message-empty" }, (msg) => {
      const iconEl = msg.createEl("div", { cls: "csc-message-icon" });
      (0, import_obsidian2.setIcon)(iconEl, "filter");
      msg.createEl("div", { cls: "csc-message-content" }, (content) => {
        content.createEl("div", { text: "当前筛选无结果", cls: "csc-message-title" });
        content.createEl("div", { text: "该分类下没有检测到问题", cls: "csc-message-desc" });
      });
    });
  }
  renderResults(container) {
    container.createEl("div", { cls: "csc-result-list" }, (list) => {
      this.filteredResults.forEach((result, index) => {
        this.renderResultCard(list, result, index);
      });
    });
  }
  renderResultCard(container, result, index) {
    const globalIndex = this.results.indexOf(result);
    container.createEl("div", { cls: "csc-result-card" }, (card) => {
      card.createEl("div", { cls: "csc-card-header" }, (header) => {
        header.createEl("div", { cls: "csc-card-index" }, (indexEl) => {
          indexEl.createEl("span", { text: String(globalIndex + 1) });
        });
        header.createEl("div", { cls: `csc-card-category csc-category-${result.category}` }, (catEl) => {
          catEl.createEl("span", { text: CATEGORY_LABELS[result.category] });
        });
      });
      const context = this.extractContext(result.offset, result.original.length);
      if (context) {
        card.createEl("div", { cls: "csc-card-context" }, (ctx) => {
          if (context.before) {
            ctx.createEl("span", { text: context.before, cls: "csc-context-before" });
          }
          ctx.createEl("span", { text: context.error, cls: "csc-context-error" });
          if (context.after) {
            ctx.createEl("span", { text: context.after, cls: "csc-context-after" });
          }
        });
      }
      card.createEl("div", { cls: "csc-card-error" }, (error) => {
        error.createEl("div", { cls: "csc-error-row" }, (row) => {
          row.createEl("span", { text: "原文：", cls: "csc-error-label" });
          row.createEl("span", { text: result.original, cls: "csc-error-text" });
        });
        error.createEl("div", { cls: "csc-arrow" }, (arrow) => {
          (0, import_obsidian2.setIcon)(arrow, "arrow-down");
        });
        error.createEl("div", { cls: "csc-correct-row" }, (row) => {
          row.createEl("span", { text: "建议：", cls: "csc-correct-label" });
          row.createEl("span", { text: result.suggestions[0], cls: "csc-correct-text" });
        });
      });
      if (result.reason) {
        card.createEl("div", { cls: "csc-card-reason" }, (reason) => {
          const iconEl = reason.createEl("div", { cls: "csc-reason-icon" });
          (0, import_obsidian2.setIcon)(iconEl, "info");
          reason.createEl("span", { text: result.reason });
        });
      }
      card.createEl("div", { cls: "csc-card-actions" }, (actions) => {
        result.suggestions.forEach((suggestion) => {
          actions.createEl("button", {
            text: `替换为「${suggestion}」`,
            cls: "csc-action-btn csc-action-apply"
          }, (btn) => {
            btn.addEventListener("click", () => {
              this.applyFix(result, suggestion, globalIndex);
            });
          });
        });
        actions.createEl("button", {
          cls: "csc-action-btn csc-action-ignore"
        }, (btn) => {
          (0, import_obsidian2.setIcon)(btn.createEl("div", { cls: "csc-btn-icon-small" }), "x");
          btn.createEl("span", { text: "忽略" });
          btn.addEventListener("click", () => {
            this.ignoreWord(result.original, globalIndex);
          });
        });
      });
    });
  }
  renderFooter(container) {
    if (this.filteredResults.length === 0 && this.results.length === 0)
      return;
    container.createEl("div", { cls: "csc-footer" }, (footer) => {
      if (this.filteredResults.length > 0) {
        footer.createEl("button", {
          cls: "csc-footer-btn csc-footer-apply"
        }, (btn) => {
          (0, import_obsidian2.setIcon)(btn.createEl("div", { cls: "csc-btn-icon" }), "check");
          btn.createEl("span", { text: `替换筛选结果 (${this.filteredResults.length})` });
          btn.addEventListener("click", () => {
            this.applyFilteredFixes();
          });
        });
        footer.createEl("button", {
          cls: "csc-footer-btn csc-footer-ignore"
        }, (btn) => {
          (0, import_obsidian2.setIcon)(btn.createEl("div", { cls: "csc-btn-icon" }), "x-circle");
          btn.createEl("span", { text: "全部忽略" });
          btn.addEventListener("click", () => {
            this.ignoreAllWords();
          });
        });
      }
      if (this.results.length > 0) {
        footer.createEl("button", {
          cls: "csc-footer-btn csc-footer-clear"
        }, (btn) => {
          (0, import_obsidian2.setIcon)(btn.createEl("div", { cls: "csc-btn-icon" }), "eraser");
          btn.createEl("span", { text: "清除高亮" });
          btn.addEventListener("click", () => {
            this.clearHighlights();
          });
        });
      }
    });
  }
  startDetection() {
    this.activeFilter = "all";
    this.plugin.startDetection();
  }
  applyFix(result, replacement, index) {
    const success = this.plugin.applyFix(result, replacement);
    if (success) {
      this.results = this.plugin.getResults();
      this.originalText = this.plugin.getOriginalText() || this.originalText;
      this.applyFilter();
      this.render();
    }
  }
  ignoreWord(word, index) {
    if (!this.plugin.settings.ignoredWords.includes(word)) {
      this.plugin.settings.ignoredWords.push(word);
      this.plugin.saveSettings();
    }
    this.results.splice(index, 1);
    this.applyFilter();
    this.render();
  }
  applyFilteredFixes() {
    const editor = this.plugin.getEditor();
    if (!editor)
      return;
    const resultKey = (r) => r.paragraphIndex !== void 0 ? r.paragraphIndex * 1e7 + r.offsetInParagraph : r.offset;
    const sortedResults = [...this.filteredResults].sort((a, b) => resultKey(b) - resultKey(a));
    let successCount = 0;
    this.plugin.restoreScroll(() => {
      for (const result of sortedResults) {
        if (result.suggestions.length === 0)
          continue;
        const replacement = result.suggestions[0];
        const loc = this.plugin.locateResultInEditor(editor, result);
        if (!loc)
          continue;
        try {
          const currentText = editor.getRange(loc.from, loc.to);
          if (currentText === result.original) {
            editor.replaceRange(replacement, loc.from, loc.to);
            successCount++;
          }
        } catch (error) {
          console.error("Apply fix error:", error);
        }
      }
    });
    this.results = [];
    this.filteredResults = [];
    this.activeFilter = "all";
    this.originalText = "";
    if (this.plugin.refreshTimer) {
      clearTimeout(this.plugin.refreshTimer);
      this.plugin.refreshTimer = null;
    }
    this.render();
    new import_obsidian2.Notice(`已修复 ${successCount} 处问题`);
  }
  ignoreAllWords() {
    this.results.forEach((result) => {
      if (!this.plugin.settings.ignoredWords.includes(result.original)) {
        this.plugin.settings.ignoredWords.push(result.original);
      }
    });
    this.plugin.saveSettings();
    this.results = [];
    this.filteredResults = [];
    this.activeFilter = "all";
    this.render();
  }
  clearHighlights() {
    this.plugin.clearAllHighlights();
    this.results = [];
    this.filteredResults = [];
    this.activeFilter = "all";
    this.render();
  }
};

// src/detector/scheduler.ts
var import_obsidian4 = require("obsidian");

// src/text/extractor.ts
var import_obsidian3 = require("obsidian");
var TextExtractor = class {
  constructor(app) {
    this.app = app;
  }
  extractText() {
    const mdView = this.getMarkdownView();
    if (!mdView) {
      return null;
    }
    const editor = mdView.editor;
    if (!editor) {
      return null;
    }
    const selection = editor.getSelection();
    if (selection && selection.length > 0) {
      const from = editor.posToOffset(editor.getCursor("from"));
      const to = editor.posToOffset(editor.getCursor("to"));
      return {
        text: selection,
        hasSelection: true,
        selectionRange: { from, to }
      };
    }
    return {
      text: editor.getValue(),
      hasSelection: false
    };
  }
  getMarkdownView() {
    const activeView = this.app.workspace.getActiveViewOfType(import_obsidian3.MarkdownView);
    if (activeView) {
      return activeView;
    }
    const leaves = this.app.workspace.getLeavesOfType("markdown");
    for (const leaf of leaves) {
      const view = leaf.view;
      if (view instanceof import_obsidian3.MarkdownView && view.getMode() === "source") {
        return view;
      }
    }
    for (const leaf of leaves) {
      const view = leaf.view;
      if (view instanceof import_obsidian3.MarkdownView) {
        return view;
      }
    }
    return null;
  }
};

// src/text/cleaner.ts
var TextCleaner = class {
  clean(originalText) {
    let text = originalText;
    const mappings = [];
    let cleanOffset = 0;
    let originalOffset = 0;
    const processedText = this.processText(text, originalOffset, cleanOffset, mappings);
    return {
      text: processedText.text,
      mappings: processedText.mappings
    };
  }
  processText(text, startOriginalOffset, startCleanOffset, mappings) {
    let result = "";
    let cleanOffset = startCleanOffset;
    let originalOffset = startOriginalOffset;
    let i = 0;
    while (i < text.length) {
      const yamlResult = this.tryExtractYamlFrontMatter(text, i);
      if (yamlResult) {
        for (let j = 0; j < yamlResult.length; j++) {
          mappings.push({
            cleanOffset: -1,
            originalOffset: originalOffset + j
          });
        }
        originalOffset += yamlResult.length;
        i += yamlResult.length;
        continue;
      }
      const codeBlockResult = this.tryExtractCodeBlock(text, i);
      if (codeBlockResult) {
        for (let j = 0; j < codeBlockResult.length; j++) {
          mappings.push({
            cleanOffset: -1,
            originalOffset: originalOffset + j
          });
        }
        originalOffset += codeBlockResult.length;
        i += codeBlockResult.length;
        continue;
      }
      const inlineCodeResult = this.tryExtractInlineCode(text, i);
      if (inlineCodeResult) {
        for (let j = 0; j < inlineCodeResult.length; j++) {
          mappings.push({
            cleanOffset: -1,
            originalOffset: originalOffset + j
          });
        }
        originalOffset += inlineCodeResult.length;
        i += inlineCodeResult.length;
        continue;
      }
      const htmlResult = this.tryExtractHtmlTag(text, i);
      if (htmlResult) {
        for (let j = 0; j < htmlResult.length; j++) {
          mappings.push({
            cleanOffset: -1,
            originalOffset: originalOffset + j
          });
        }
        originalOffset += htmlResult.length;
        i += htmlResult.length;
        continue;
      }
      const linkResult = this.tryExtractLink(text, i);
      if (linkResult) {
        const displayText = linkResult.displayText;
        for (let j = 0; j < linkResult.urlPart.length; j++) {
          mappings.push({
            cleanOffset: -1,
            originalOffset: originalOffset + j
          });
        }
        originalOffset += linkResult.urlPart.length;
        i += linkResult.urlPart.length;
        for (let j = 0; j < displayText.length; j++) {
          mappings.push({
            cleanOffset: cleanOffset + j,
            originalOffset: originalOffset + j
          });
        }
        result += displayText;
        cleanOffset += displayText.length;
        originalOffset += displayText.length;
        i += displayText.length;
        continue;
      }
      mappings.push({
        cleanOffset,
        originalOffset
      });
      result += text[i];
      cleanOffset++;
      originalOffset++;
      i++;
    }
    return { text: result, mappings };
  }
  tryExtractYamlFrontMatter(text, start) {
    if (start !== 0)
      return null;
    if (!text.startsWith("---", start))
      return null;
    const endIndex = text.indexOf("---", 3);
    if (endIndex === -1)
      return null;
    return text.substring(start, endIndex + 3);
  }
  tryExtractCodeBlock(text, start) {
    if (!text.startsWith("```", start))
      return null;
    const endIndex = text.indexOf("```", start + 3);
    if (endIndex === -1)
      return null;
    return text.substring(start, endIndex + 3);
  }
  tryExtractInlineCode(text, start) {
    if (text[start] !== "`")
      return null;
    if (text.startsWith("```", start))
      return null;
    const endIndex = text.indexOf("`", start + 1);
    if (endIndex === -1)
      return null;
    return text.substring(start, endIndex + 1);
  }
  tryExtractHtmlTag(text, start) {
    if (text[start] !== "<")
      return null;
    const endIndex = text.indexOf(">", start);
    if (endIndex === -1)
      return null;
    return text.substring(start, endIndex + 1);
  }
  tryExtractLink(text, start) {
    const linkRegex = /^\[([^\]]*)\]\(([^)]+)\)/;
    const match = text.substring(start).match(linkRegex);
    if (!match)
      return null;
    const fullMatch = match[0];
    const displayText = match[1];
    const urlPart = fullMatch.substring(fullMatch.indexOf("]("));
    return {
      urlPart: `](${match[2]})`,
      displayText
    };
  }
};

// src/text/mapper.ts
var OffsetMapper = class {
  constructor(mappings) {
    this.mappings = mappings;
  }
  cleanOffsetToOriginal(cleanOffset) {
    for (let i = 0; i < this.mappings.length; i++) {
      if (this.mappings[i].cleanOffset === cleanOffset) {
        return this.mappings[i].originalOffset;
      }
    }
    for (let i = this.mappings.length - 1; i >= 0; i--) {
      if (this.mappings[i].cleanOffset !== -1 && this.mappings[i].cleanOffset < cleanOffset) {
        const diff = cleanOffset - this.mappings[i].cleanOffset;
        return this.mappings[i].originalOffset + diff;
      }
    }
    return cleanOffset;
  }
  originalOffsetToClean(originalOffset) {
    for (let i = 0; i < this.mappings.length; i++) {
      if (this.mappings[i].originalOffset === originalOffset) {
        return this.mappings[i].cleanOffset;
      }
    }
    for (let i = this.mappings.length - 1; i >= 0; i--) {
      if (this.mappings[i].originalOffset < originalOffset) {
        const diff = originalOffset - this.mappings[i].originalOffset;
        const targetClean = this.mappings[i].cleanOffset + diff;
        if (targetClean >= 0) {
          return targetClean;
        }
      }
    }
    return originalOffset;
  }
  isValidCleanOffset(offset) {
    return offset >= 0 && offset < this.mappings.length;
  }
  isValidOriginalOffset(offset) {
    var _a;
    return this.mappings.some((m) => m.originalOffset === offset) || offset >= 0 && offset <= ((_a = this.mappings[this.mappings.length - 1]) == null ? void 0 : _a.originalOffset);
  }
};
function splitParagraphs(text) {
  const paragraphs = [];
  const re = /\n\s*\n/g;
  let start = 0;
  let match;
  while ((match = re.exec(text)) !== null) {
    if (match.index > start) {
      paragraphs.push({ start, end: match.index });
    }
    start = re.lastIndex;
  }
  if (start < text.length) {
    paragraphs.push({ start, end: text.length });
  }
  return paragraphs;
}
function locateParagraph(paragraphs, offset) {
  let lo = 0;
  let hi = paragraphs.length - 1;
  while (lo <= hi) {
    const mid = lo + hi >> 1;
    if (offset < paragraphs[mid].start) {
      hi = mid - 1;
    } else if (offset >= paragraphs[mid].end) {
      lo = mid + 1;
    } else {
      return mid;
    }
  }
  return -1;
}
function addParagraphOffsets(results, text) {
  if (!Array.isArray(results) || typeof text !== "string") {
    return results;
  }
  const paragraphs = splitParagraphs(text);
  return results.map((r) => {
    const idx = locateParagraph(paragraphs, r.offset);
    if (idx === -1) {
      return r;
    }
    return { ...r, paragraphIndex: idx, offsetInParagraph: r.offset - paragraphs[idx].start };
  });
}
function applyChangesToOffsets(results, ranges) {
  if (!Array.isArray(results) || !Array.isArray(ranges) || ranges.length === 0) {
    return results;
  }
  const kept = [];
  for (const r of results) {
    const rStart = r.offset;
    const rEnd = r.offset + r.original.length;
    let newOffset = r.offset;
    let invalid = false;
    for (const rg of ranges) {
      if (rEnd <= rg.fromA) {
        break;
      }
      if (rStart >= rg.toA) {
        newOffset += rg.diff;
        continue;
      }
      invalid = true;
      break;
    }
    if (invalid) {
      continue;
    }
    r.offset = newOffset;
    kept.push(r);
  }
  return kept;
}

// src/text/segmenter.ts
var TextSegmenter = class {
  constructor(maxSegmentLength = 1500) {
    this.maxSegmentLength = maxSegmentLength;
  }
  segment(text) {
    const paragraphs = this.splitByParagraphs(text);
    const segments = [];
    let currentSegment = "";
    const currentOffsets = [];
    let currentStartOffset = 0;
    let currentOffset = 0;
    for (const paragraph of paragraphs) {
      if (currentSegment.length + paragraph.text.length + 1 > this.maxSegmentLength) {
        if (currentSegment.length > 0) {
          const trimmed = currentSegment.trimStart();
          const trimOffset = currentSegment.length - trimmed.length;
          const finalText = trimmed.trimEnd();
          if (finalText.length > 0) {
            segments.push({
              text: finalText,
              startOffset: currentStartOffset + trimOffset,
              endOffset: currentOffset - (trimmed.length - finalText.length),
              offsets: currentOffsets.slice(trimOffset, trimOffset + finalText.length)
            });
          }
          currentSegment = "";
          currentOffsets.length = 0;
          currentStartOffset = currentOffset;
        }
        if (paragraph.text.length > this.maxSegmentLength) {
          const subSegments = this.splitLongParagraph(paragraph, currentStartOffset);
          segments.push(...subSegments);
          currentStartOffset = currentOffset + paragraph.text.length;
          currentOffset = currentStartOffset;
          continue;
        }
      }
      if (currentSegment.length > 0) {
        currentSegment += "\n";
        currentOffsets.push(paragraph.startOffset - 1);
        currentOffset++;
      }
      if (currentSegment.length === 0) {
        currentStartOffset = currentOffset;
      }
      for (let j = 0; j < paragraph.text.length; j++) {
        currentOffsets.push(paragraph.startOffset + j);
      }
      currentSegment += paragraph.text;
      currentOffset += paragraph.text.length;
    }
    if (currentSegment.trim().length > 0) {
      const trimmed = currentSegment.trimStart();
      const trimOffset = currentSegment.length - trimmed.length;
      const finalText = trimmed.trimEnd();
      if (finalText.length > 0) {
        segments.push({
          text: finalText,
          startOffset: currentStartOffset + trimOffset,
          endOffset: currentOffset - (trimmed.length - finalText.length),
          offsets: currentOffsets.slice(trimOffset, trimOffset + finalText.length)
        });
      }
    }
    return segments;
  }
  splitByParagraphs(text) {
    const paragraphs = [];
    const re = /\n\s*\n/g;
    let start = 0;
    let match;
    while ((match = re.exec(text)) !== null) {
      if (match.index > start) {
        paragraphs.push({
          text: text.slice(start, match.index),
          startOffset: start,
          endOffset: match.index
        });
      }
      start = re.lastIndex;
    }
    if (start < text.length) {
      paragraphs.push({
        text: text.slice(start),
        startOffset: start,
        endOffset: text.length
      });
    }
    return paragraphs;
  }
  splitLongParagraph(paragraph, startOffset) {
    const segments = [];
    const sentences = this.splitBySentences(paragraph.text);
    let currentSegment = "";
    const currentOffsets = [];
    let currentStartOffset = startOffset;
    let currentOffset = startOffset;
    for (const sentence of sentences) {
      const sentenceCleanStart = paragraph.startOffset + sentence.startOffset;
      if (currentSegment.length + sentence.text.length > this.maxSegmentLength) {
        if (currentSegment.length > 0) {
          const trimmed = currentSegment.trimStart();
          const trimOffset = currentSegment.length - trimmed.length;
          const finalText = trimmed.trimEnd();
          if (finalText.length > 0) {
            segments.push({
              text: finalText,
              startOffset: currentStartOffset + trimOffset,
              endOffset: currentOffset - (trimmed.length - finalText.length),
              offsets: currentOffsets.slice(trimOffset, trimOffset + finalText.length)
            });
          }
          currentSegment = "";
          currentOffsets.length = 0;
          currentStartOffset = currentOffset;
        }
        if (sentence.text.length > this.maxSegmentLength) {
          const chunks = this.splitByLength(sentence.text, this.maxSegmentLength);
          for (let ci = 0; ci < chunks.length; ci++) {
            const chunk = chunks[ci];
            const chunkCleanStart = sentenceCleanStart + ci * this.maxSegmentLength;
            const trimmedChunk = chunk.trim();
            if (trimmedChunk.length > 0) {
              const chunkTrimOffset = chunk.length - chunk.trimStart().length;
              const chunkCleanOffsets = [];
              for (let j = chunkTrimOffset; j < chunk.length - (chunk.length - chunk.trimEnd().length); j++) {
                chunkCleanOffsets.push(chunkCleanStart + j);
              }
              segments.push({
                text: trimmedChunk,
                startOffset: currentStartOffset + chunkTrimOffset,
                endOffset: currentStartOffset + chunk.length - (chunk.length - chunk.trimEnd().length),
                offsets: chunkCleanOffsets
              });
            }
            currentStartOffset += chunk.length;
            currentOffset = currentStartOffset;
          }
          continue;
        }
      }
      if (currentSegment.length === 0) {
        currentStartOffset = currentOffset;
      }
      for (let j = 0; j < sentence.text.length; j++) {
        currentOffsets.push(sentenceCleanStart + j);
      }
      currentSegment += sentence.text;
      currentOffset += sentence.text.length;
    }
    if (currentSegment.trim().length > 0) {
      const trimmed = currentSegment.trimStart();
      const trimOffset = currentSegment.length - trimmed.length;
      const finalText = trimmed.trimEnd();
      if (finalText.length > 0) {
        segments.push({
          text: finalText,
          startOffset: currentStartOffset + trimOffset,
          endOffset: currentOffset - (trimmed.length - finalText.length),
          offsets: currentOffsets.slice(trimOffset, trimOffset + finalText.length)
        });
      }
    }
    return segments;
  }
  splitBySentences(text) {
    const sentences = [];
    let start = 0;
    for (let i = 0; i < text.length; i++) {
      if (text[i] === "。" || text[i] === "！" || text[i] === "？" || text[i] === "；" || text[i] === "\n") {
        const sentenceText = text.slice(start, i + 1);
        if (sentenceText.trim().length > 0) {
          sentences.push({ text: sentenceText, startOffset: start });
        }
        start = i + 1;
      }
    }
    if (start < text.length) {
      const sentenceText = text.slice(start);
      if (sentenceText.trim().length > 0) {
        sentences.push({ text: sentenceText, startOffset: start });
      }
    }
    return sentences;
  }
  splitByLength(text, maxLength) {
    const chunks = [];
    for (let i = 0; i < text.length; i += maxLength) {
      chunks.push(text.substring(i, i + maxLength));
    }
    return chunks;
  }
};

// src/engines/aiDetector.ts
var CATEGORY_MAP = {
  typo: "typo",
  particle: "typo",
  punctuation: "punctuation",
  grammar: "grammar"
};
var BUILT_IN_PHRASE_DICTIONARY = [
  "迫不急待 => 迫不及待",
  "一如继往 => 一如既往",
  "默守成规 => 墨守成规",
  "走头无路 => 走投无路"
];
function parsePhraseDictionary(builtIns, userLines) {
  const entries = /* @__PURE__ */ new Map();
  const addEntries = (lines) => {
    for (const line of Array.isArray(lines) ? lines : []) {
      if (typeof line !== "string")
        continue;
      const arrowIndex = line.indexOf("=>");
      if (arrowIndex === -1)
        continue;
      const original = line.slice(0, arrowIndex).trim();
      const correct = line.slice(arrowIndex + 2).trim();
      if (!original || !correct || original === correct)
        continue;
      entries.set(original, { original, correct });
    }
  };
  addEntries(builtIns);
  addEntries(userLines);
  return [...entries.values()];
}
function findPhraseMatches(text, entries) {
  if (typeof text !== "string" || !Array.isArray(entries))
    return [];
  const matches = [];
  let start = 0;
  while (start < text.length) {
    let match = null;
    for (const entry of entries) {
      if (!entry || typeof entry.original !== "string" || entry.original.length === 0)
        continue;
      if (text.startsWith(entry.original, start)) {
        match = entry;
        break;
      }
    }
    if (match) {
      const end = start + match.original.length;
      matches.push({ start, end, original: match.original, correct: match.correct });
      start = end;
    } else {
      start++;
    }
  }
  return matches;
}
function detectPhraseErrors(segment, entries) {
  if (!segment || typeof segment.text !== "string" || !Number.isInteger(segment.startOffset))
    return [];
  return findPhraseMatches(segment.text, entries).map((match) => ({
    offset: segment.offsets ? segment.offsets[match.start] : segment.startOffset + match.start,
    original: match.original,
    suggestions: [match.correct],
    reason: "固定词组用字错误",
    source: "dictionary",
    category: "typo"
  }));
}
function validateAIResult(text, result) {
  if (typeof text !== "string" || !result || typeof result !== "object")
    return null;
  const { start, end, original } = result;
  if (!Number.isInteger(start) || !Number.isInteger(end) || start < 0 || end <= start || end > text.length || typeof original !== "string")
    return null;
  return text.slice(start, end) === original ? result : null;
}
function toDetectionResult(text, baseOffset, item) {
  const valid = validateAIResult(text, item);
  if (!valid) {
    return null;
  }
  return {
    offset: baseOffset + valid.start,
    original: valid.original,
    suggestions: [valid.correct],
    reason: valid.reason,
    source: "ai",
    category: valid.category
  };
}
function locateUniqueOriginal(text, original) {
  if (typeof text !== "string" || typeof original !== "string" || original.length === 0)
    return null;
  const first = text.indexOf(original);
  if (first === -1 || text.indexOf(original, first + 1) !== -1)
    return null;
  return { start: first, end: first + original.length };
}
var AIDetector = class {
  constructor(settings) {
    this.settings = settings;
  }
  async detectSegment(segment) {
    if (!this.settings.apiKey) {
      throw new Error("API Key 未配置");
    }
    const prompt = this.buildPrompt(segment.text, this.settings.detectionMode);
    let lastError = null;
    for (let attempt = 0; attempt < 3; attempt++) {
      if (attempt > 0) {
        await new Promise((resolve) => setTimeout(resolve, 1200 * attempt));
      }
      try {
        const response = await this.callAPI(prompt);
        const parsed = this.parseResponse(response);
        if (parsed.parseError) {
          lastError = new Error("AI 响应为空或格式异常");
          continue;
        }
        const results = [];
        const seen = /* @__PURE__ */ new Set();
        for (const r of parsed.results) {
          let result = toDetectionResult(segment.text, 0, r);
          if (result) {
            result = { ...result, offset: segment.offsets ? segment.offsets[r.start] : segment.startOffset + r.start };
          }
          if (!result) {
            const located = locateUniqueOriginal(segment.text, r.original);
            if (located) {
              result = toDetectionResult(segment.text, 0, { ...r, ...located });
              if (result) {
                result = { ...result, offset: segment.offsets ? segment.offsets[located.start] : segment.startOffset + located.start };
              }
            }
          }
          if (result && result.suggestions[0] !== result.original) {
            const key = `${result.offset}|${result.original}|${result.suggestions[0]}`;
            if (!seen.has(key)) {
              seen.add(key);
              results.push({ ...result, category: this.normalizeCategory(result.category) });
            }
          }
        }
        return results;
      } catch (error) {
        lastError = error;
        console.error(`AI detection error (attempt ${attempt + 1}/3):`, error);
      }
    }
    throw lastError || new Error("AI 检测失败");
  }
  async detectSegments(segments, onProgress) {
    const allResults = [];
    let failedCount = 0;
    const phraseEntries = parsePhraseDictionary(BUILT_IN_PHRASE_DICTIONARY, this.settings.phraseDictionary);
    for (let i = 0; i < segments.length; i++) {
      if (onProgress) {
        onProgress(i + 1, segments.length);
      }
      const phraseResults = detectPhraseErrors(segments[i], phraseEntries);
      allResults.push(...phraseResults);
      try {
        const results = await this.detectSegment(segments[i]);
        allResults.push(...results);
      } catch (error) {
        failedCount++;
        console.error(`Error detecting segment ${i}:`, error);
      }
    }
    return { results: allResults, failedCount };
  }
  normalizeCategory(raw) {
    if (!raw)
      return "typo";
    const lower = raw.toLowerCase().trim();
    if (CATEGORY_MAP[lower])
      return CATEGORY_MAP[lower];
    if (lower.includes("标点") || lower.includes("punct"))
      return "punctuation";
    if (lower.includes("语法") || lower.includes("gram"))
      return "grammar";
    return "typo";
  }
  buildPrompt(text, mode) {
    const baseInstruction = `你是中文出版级校对助手，直接给出结论，不要思考过程。

重点任务（优先级最高）：
1. 检查“的、地、得”的误用：
   - “的”通常连接定语和名词：美丽的风景
   - “地”通常连接状语和动词：认真地学习、慢慢地走
   - “得”通常置于动词或形容词后补充程度、结果：跑得快、写得很好
   - 只有在结合完整短语和句法后能确定错误时才报告
   - 报告时 original 必须包含足以判断的完整短语，不能只返回单个“的”“地”或“得”
2. 检查固定词组、成语、惯用搭配中的别字，例如：迫不及待（不是“迫不急待”）、一如既往（不是“一如即往”）、相辅相成（不是“相辅相承”）
3. 不把文学表达、人物名、地名、专有名词、方言或刻意口语化当作错误`;
    let taskInstruction = "";
    let categoryInstruction = "";
    switch (mode) {
      case "quick":
        taskInstruction = `本次只检查：错别字（音近字、形近字、笔误）、“的、地、得”误用、固定词组用字错误。`;
        categoryInstruction = `category 固定填 "typo"（“的、地、得”误用同样填 "typo"）。`;
        break;
      case "standard":
        taskInstruction = `本次检查以下问题：
1. 错别字（音近字、形近字、笔误）
2. “的、地、得”误用
3. 固定词组、成语、惯用搭配用字错误
4. 标点符号错误：中英文标点混用、连续重复标点、缺失标点、标点位置错误
5. 明显语法错误：搭配不当、成分残缺、语序不当、重复赘余`;
        categoryInstruction = `category 根据问题类型填写："typo"（错别字、固定词组、“的、地、得”误用）、"punctuation"（标点符号）、"grammar"（语法错误）。`;
        break;
      case "deep":
        taskInstruction = `本次检查以下问题：
1. 错别字（音近字、形近字、笔误）
2. “的、地、得”误用
3. 固定词组、成语、惯用搭配用字错误
4. 标点符号错误：中英文标点混用、连续重复标点、缺失标点、标点位置错误
5. 语法错误：搭配不当、成分残缺、语序不当、重复赘余
6. 谨慎的表达优化：口语化表达改为书面语、相邻句重复用词（仅当明显时才报告）`;
        categoryInstruction = `category 根据问题类型填写："typo"（含“的、地、得”误用）、"punctuation"、"grammar"。表达优化类归入 "grammar"。`;
        break;
    }
    return `${baseInstruction}
${taskInstruction}

文本：
${text}

请严格按照以下 JSON 数组格式返回结果，不要返回任何其他文字：
[{"start": 0, "end": 4, "original": "公作", "correct": "工作", "reason": "同音字误用", "category": "typo"}]

注意：
1. start、end 是问题片段在文本中的从零开始字符下标，end 不包含在片段内
2. original 必须与下标完全一致（text.slice(start, end) === original）
3. correct 是建议的正确内容
4. reason 是简要的纠错原因（不超过 20 个字）
5. ${categoryInstruction}
6. “的、地、得”误用必须上报包含完整短语的 original，不能只返回单个“的”“地”或“得”
7. 如果没有发现问题，返回空数组 []
8. 保持原意，不要改动文学性修辞、专有名词、人名地名、方言或刻意口语化
9. 只返回确定有问题的，不确定的不返回
10. 结果条目不超过 20 条
11. 只返回 JSON 数组，不要有任何其他输出`;
  }
  findWordInText(word, text, baseOffset) {
    const results = [];
    if (!word || word.length === 0) {
      return results;
    }
    let startIndex = 0;
    while (true) {
      const index = text.indexOf(word, startIndex);
      if (index === -1)
        break;
      results.push({
        offset: baseOffset + index
      });
      startIndex = index + 1;
    }
    return results;
  }
  async callAPI(prompt) {
    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), this.settings.timeout);
    try {
      const response = await fetch(this.settings.apiEndpoint, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "Authorization": `Bearer ${this.settings.apiKey}`
        },
        body: JSON.stringify({
          model: this.settings.modelName,
          messages: [
            {
              role: "system",
              content: "你是中文出版级校对助手，专门识别错别字、“的、地、得”误用、固定词组用字、标点错误和语法问题。你只返回 JSON 格式的结果，不返回任何其他内容。"
            },
            {
              role: "user",
              content: prompt
            }
          ],
          temperature: 0.1,
          max_tokens: 8e3,
          thinking: { type: "disabled" }
        }),
        signal: controller.signal
      });
      clearTimeout(timeoutId);
      if (!response.ok) {
        const errorText = await response.text();
        throw new Error(`API 请求失败: ${response.status} - ${errorText}`);
      }
      const data = await response.json();
      if (!data.choices || !data.choices[0] || !data.choices[0].message) {
        throw new Error("API 返回格式错误");
      }
      const choice = data.choices[0];
      const content = choice.message.content;
      if (typeof content !== "string" || content.trim().length === 0 || choice.finish_reason === "length") {
        throw new Error("API 输出为空或超出长度限制");
      }
      return content;
    } catch (error) {
      clearTimeout(timeoutId);
      if (error instanceof Error && error.name === "AbortError") {
        throw new Error("API 请求超时");
      }
      throw error;
    }
  }
  parseResponse(response) {
    if (typeof response !== "string" || !response.trim()) {
      console.error("Failed to parse AI response: empty content");
      return { results: [], parseError: true };
    }
    try {
      let jsonStr = response.trim();
      const jsonMatch = jsonStr.match(/\[[\s\S]*\]/);
      if (jsonMatch) {
        jsonStr = jsonMatch[0];
      }
      const results = JSON.parse(jsonStr);
      if (!Array.isArray(results)) {
        throw new Error("返回结果不是数组");
      }
      const validResults = results.filter(
        (r) => typeof r.original === "string" && typeof r.correct === "string" && r.original.length > 0 && r.correct.length > 0 && Number.isInteger(r.start) && Number.isInteger(r.end) && r.start >= 0 && r.end > r.start
      );
      return { results: validResults, parseError: false };
    } catch (error) {
      console.error("Failed to parse AI response:", response);
      return { results: [], parseError: true };
    }
  }
  updateSettings(settings) {
    this.settings = settings;
  }
};

// src/detector/scheduler.ts
var DetectionScheduler = class {
  constructor(settings, app) {
    this.onProgress = null;
    this.settings = settings;
    this.textExtractor = new TextExtractor(app);
    this.textCleaner = new TextCleaner();
    this.textSegmenter = new TextSegmenter(settings.maxSegmentLength);
    this.aiDetector = new AIDetector(settings);
  }
  setProgressCallback(callback) {
    this.onProgress = callback;
  }
  async detect() {
    this.reportProgress({ status: "detecting", currentStep: "提取文本..." });
    const extractionResult = this.textExtractor.extractText();
    if (!extractionResult) {
      throw new Error("无法获取当前文档内容");
    }
    const originalText = extractionResult.text;
    const hasSelection = extractionResult.hasSelection;
    const selectionRange = extractionResult.selectionRange;
    this.reportProgress({ status: "detecting", currentStep: "清洗文本..." });
    const cleanResult = this.textCleaner.clean(originalText);
    const cleanedText = cleanResult.text;
    const mapper = new OffsetMapper(cleanResult.mappings);
    const allResults = [];
    if (this.settings.apiKey) {
      this.reportProgress({ status: "detecting", currentStep: "准备 AI 检测..." });
      const segments = this.textSegmenter.segment(cleanedText);
      if (segments.length > 0) {
        this.reportProgress({
          status: "detecting",
          currentStep: "AI 引擎检测中...",
          aiProgress: { current: 0, total: segments.length }
        });
        try {
          const aiOutcome = await this.aiDetector.detectSegments(segments, (current, total) => {
            this.reportProgress({
              status: "detecting",
              currentStep: "AI 引擎检测中...",
              aiProgress: { current, total }
            });
          });
          for (const result of aiOutcome.results) {
            if (!this.settings.ignoredWords.includes(result.original)) {
              const originalOffset = mapper.cleanOffsetToOriginal(result.offset);
              allResults.push({
                ...result,
                offset: originalOffset
              });
            }
          }
          if (aiOutcome.failedCount > 0) {
            new import_obsidian4.Notice(`AI 检测不完整：${aiOutcome.failedCount} 个分段响应异常（已重试），结果可能漏检`);
          }
        } catch (error) {
          console.error("AI detection error:", error);
          new import_obsidian4.Notice("AI 检测失败，请检查 API 配置");
          throw error;
        }
      }
    }
    allResults.sort((a, b) => a.offset - b.offset);
    let filteredResults = allResults;
    if (hasSelection && selectionRange) {
      filteredResults = allResults.filter(
        (r) => r.offset >= selectionRange.from && r.offset < selectionRange.to
      );
    }
    return addParagraphOffsets(filteredResults, originalText);
  }
  reportProgress(progress) {
    if (this.onProgress) {
      this.onProgress(progress);
    }
  }
  updateSettings(settings) {
    this.settings = settings;
    this.textSegmenter = new TextSegmenter(settings.maxSegmentLength);
    this.aiDetector.updateSettings(settings);
  }
};

// src/editor/highlight.ts
var import_view = require("@codemirror/view");
var import_state = require("@codemirror/state");
var setHighlightsEffect = import_state.StateEffect.define();
var clearHighlightsEffect = import_state.StateEffect.define();
function getCategoryClass(category) {
  switch (category) {
    case "typo":
      return "csc-highlight-typo";
    case "punctuation":
      return "csc-highlight-punctuation";
    case "grammar":
      return "csc-highlight-grammar";
    default:
      return "csc-highlight-typo";
  }
}
function buildDecorationsFromResults(results, docLength) {
  const builder = new import_state.RangeSetBuilder();
  if (results.length === 0) {
    return builder.finish();
  }
  const sortedResults = [...results].sort((a, b) => a.offset - b.offset);
  for (const result of sortedResults) {
    const from = result.offset;
    const to = result.offset + result.original.length;
    if (from >= 0 && to <= docLength && from < to) {
      const decoration = import_view.Decoration.mark({
        class: getCategoryClass(result.category)
      });
      builder.add(from, to, decoration);
    }
  }
  return builder.finish();
}
var highlightsField = import_state.StateField.define({
  create: () => import_view.Decoration.none,
  update: (decorations, tr) => {
    decorations = decorations.map(tr.changes);
    for (const effect of tr.effects) {
      if (effect.is(setHighlightsEffect)) {
        return buildDecorationsFromResults(effect.value, tr.newDoc.length);
      }
      if (effect.is(clearHighlightsEffect)) {
        return import_view.Decoration.none;
      }
    }
    return decorations;
  },
  provide: (f) => import_view.EditorView.decorations.from(f)
});
var highlightTheme = import_view.EditorView.baseTheme({
  ".csc-highlight-typo": {
    backgroundColor: "rgba(230, 57, 70, 0.15)",
    borderBottom: "2px wavy rgba(230, 57, 70, 0.7)"
  },
  ".csc-highlight-punctuation": {
    backgroundColor: "rgba(230, 167, 0, 0.15)",
    borderBottom: "2px wavy rgba(230, 167, 0, 0.7)"
  },
  ".csc-highlight-grammar": {
    backgroundColor: "rgba(86, 156, 214, 0.15)",
    borderBottom: "2px wavy rgba(86, 156, 214, 0.7)"
  }
});
function setHighlights(view, results) {
  view.dispatch({
    effects: setHighlightsEffect.of(results)
  });
}
function clearHighlights(view) {
  view.dispatch({
    effects: clearHighlightsEffect.of(void 0)
  });
}

// src/main.ts
var CSCPlugin = class extends import_obsidian5.Plugin {
  constructor() {
    super(...arguments);
    this.view = null;
    this.scheduler = null;
    this.detectionResults = [];
    this.originalText = "";
  }
  async onload() {
    await this.loadSettings();
    await this.syncLicenseStatus();
    this.scheduler = new DetectionScheduler(this.settings, this.app);
    this.registerEditorExtension([highlightsField, highlightTheme, import_view.EditorView.updateListener.of((update) => {
      if (update.docChanged) {
        this.handleDocChanged(update);
      }
    })]);
    this.registerView(VIEW_TYPE_CSC, (leaf) => {
      this.view = new CSCView(leaf, this);
      return this.view;
    });
    this.addRibbonIcon("spell-check", "中文校对", () => {
      this.activateView();
    });
    this.addCommand({
      id: "check-chinese-typos",
      name: "检测当前文档",
      callback: () => {
        this.startDetection();
      }
    });
    this.addCommand({
      id: "clear-highlights",
      name: "清除编辑器高亮",
      callback: () => {
        this.clearAllHighlights();
      }
    });
    this.addSettingTab(new CSCSettingTab(this.app, this));
  }
  onunload() {
    if (this.view) {
      this.view = null;
    }
    if (this.refreshTimer) {
      clearTimeout(this.refreshTimer);
      this.refreshTimer = null;
    }
    this.scheduler = null;
    this.clearEditorHighlights();
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
    if (this.scheduler) {
      this.scheduler.updateSettings(this.settings);
    }
  }
  async syncLicenseStatus() {
    const localLicenseType = activationService.checkLocalLicenseStatus();
    if (localLicenseType !== this.settings.licenseType) {
      this.settings.licenseType = localLicenseType;
      await this.saveSettings();
    }
  }
  isFullVersion() {
    return ActivationService.isFullVersion(this.settings.licenseType);
  }
  canUseMode(mode) {
    return true;
  }
  activateView() {
    var _a;
    const leaf = this.app.workspace.getLeavesOfType(VIEW_TYPE_CSC);
    if (leaf.length > 0) {
      this.app.workspace.revealLeaf(leaf[0]);
      return;
    }
    (_a = this.app.workspace.getRightLeaf(false)) == null ? void 0 : _a.setViewState({
      type: VIEW_TYPE_CSC,
      active: true
    });
  }
  getMarkdownView() {
    const activeView = this.app.workspace.getActiveViewOfType(import_obsidian5.MarkdownView);
    if (activeView) {
      return activeView;
    }
    const leaves = this.app.workspace.getLeavesOfType("markdown");
    for (const leaf of leaves) {
      const view = leaf.view;
      if (view instanceof import_obsidian5.MarkdownView && view.getMode() === "source") {
        return view;
      }
    }
    for (const leaf of leaves) {
      const view = leaf.view;
      if (view instanceof import_obsidian5.MarkdownView) {
        return view;
      }
    }
    return null;
  }
  getEditorView() {
    var _a;
    const mdView = this.getMarkdownView();
    if (!mdView)
      return null;
    const cm = (_a = mdView.editor) == null ? void 0 : _a.cm;
    return cm || null;
  }
  restoreScroll(fn) {
    const view = this.getEditorView();
    const scrollTop = view ? view.scrollDOM.scrollTop : null;
    fn();
    if (view && scrollTop != null) {
      // 替换触发 CM6 光标可见性滚动，恢复 scrollTop 使视口内容保持原位
      view.scrollDOM.scrollTop = scrollTop;
    }
  }
  async startDetection() {
    const activeFile = this.app.workspace.getActiveFile();
    if (!activeFile) {
      new import_obsidian5.Notice("没有打开的文档");
      return;
    }
    const mdView = this.getMarkdownView();
    if (!mdView) {
      new import_obsidian5.Notice("当前视图不是 Markdown 编辑器");
      return;
    }
    const editor = mdView.editor;
    this.originalText = editor.getValue();
    this.clearEditorHighlights();
    this.activateView();
    if (!this.scheduler) {
      this.scheduler = new DetectionScheduler(this.settings, this.app);
    }
    if (this.view) {
      this.view.setStatus("detecting");
    }
    try {
      this.detectionResults = await this.scheduler.detect();
      if (this.view) {
        this.view.setResults(this.detectionResults, this.originalText);
        this.view.setStatus("completed");
      }
      if (this.detectionResults.length > 0) {
        const editorView = this.getEditorView();
        if (editorView) {
          setHighlights(editorView, this.detectionResults);
        }
      }
      if (this.detectionResults.length === 0) {
        new import_obsidian5.Notice("太棒了！没有发现问题");
      } else {
        new import_obsidian5.Notice(`发现 ${this.detectionResults.length} 处问题`);
      }
    } catch (error) {
      console.error("Detection error:", error);
      if (this.view) {
        this.view.setStatus("error", error instanceof Error ? error.message : "检测失败");
      }
      new import_obsidian5.Notice("检测失败: " + (error instanceof Error ? error.message : "未知错误"));
    }
  }
  locateResultInEditor(editor, result) {
    if (!editor || !result) {
      return null;
    }
    return { from: editor.offsetToPos(result.offset), to: editor.offsetToPos(result.offset + result.original.length) };
  }
  applyFix(result, replacement) {
    const editor = this.getEditor();
    if (!editor) {
      new import_obsidian5.Notice("无法获取编辑器");
      return false;
    }
    try {
      const loc = this.locateResultInEditor(editor, result);
      if (!loc) {
        new import_obsidian5.Notice("文本已被修改或位置偏移，请重新检测");
        return false;
      }
      const currentText = editor.getRange(loc.from, loc.to);
      if (currentText !== result.original) {
        console.log(`文本不匹配: 期望 "${result.original}", 实际 "${currentText}"`);
        new import_obsidian5.Notice("文本已被修改或位置偏移，请重新检测");
        return false;
      }
      // 替换会触发 CM6 updateListener → handleDocChanged 平移后续偏移并移除该项；
      // restoreScroll 抵消替换引起的光标可见性滚动，视口内容保持原位
      this.restoreScroll(() => {
        editor.replaceRange(replacement, loc.from, loc.to);
      });
      return true;
    } catch (error) {
      console.error("Apply fix error:", error);
      new import_obsidian5.Notice("修复失败");
      return false;
    }
  }
  applyAllFixes() {
    const editor = this.getEditor();
    if (!editor) {
      new import_obsidian5.Notice("无法获取编辑器");
      return 0;
    }
    const resultKey = (r) => r.paragraphIndex !== void 0 ? r.paragraphIndex * 1e7 + r.offsetInParagraph : r.offset;
    const sortedResults = [...this.detectionResults].sort((a, b) => resultKey(b) - resultKey(a));
    let successCount = 0;
    this.restoreScroll(() => {
      for (const result of sortedResults) {
        if (result.suggestions.length === 0)
          continue;
        const replacement = result.suggestions[0];
        const loc = this.locateResultInEditor(editor, result);
        if (!loc)
          continue;
        try {
          const currentText = editor.getRange(loc.from, loc.to);
          if (currentText === result.original) {
            editor.replaceRange(replacement, loc.from, loc.to);
            successCount++;
          }
        } catch (error) {
          console.error("Apply fix error:", error);
        }
      }
    });
    this.detectionResults = [];
    this.originalText = "";
    if (this.refreshTimer) {
      clearTimeout(this.refreshTimer);
      this.refreshTimer = null;
    }
    this.clearEditorHighlights();
    if (this.view) {
      this.view.setResults([]);
    }
    new import_obsidian5.Notice(`已修复 ${successCount} 处问题`);
    return successCount;
  }
  renderResults() {
    if (this.detectionResults.length > 0) {
      const editorView = this.getEditorView();
      if (editorView) {
        setHighlights(editorView, this.detectionResults);
      }
    } else {
      this.clearEditorHighlights();
    }
    if (this.view) {
      this.view.setResults(this.detectionResults);
    }
  }
  handleDocChanged(update) {
    if (this.detectionResults.length === 0) {
      return;
    }
    const ranges = [];
    update.changes.iterChanges((fromA, toA, fromB, toB, inserted) => {
      ranges.push({ fromA, toA, diff: inserted.length - (toA - fromA) });
    });
    if (ranges.length === 0) {
      return;
    }
    this.detectionResults = applyChangesToOffsets(this.detectionResults, ranges);
    if (this.refreshTimer) {
      clearTimeout(this.refreshTimer);
    }
    this.refreshTimer = setTimeout(() => {
      this.refreshTimer = null;
      this.renderResults();
    }, 150);
  }
  clearEditorHighlights() {
    const editorView = this.getEditorView();
    if (editorView) {
      clearHighlights(editorView);
    }
  }
  clearAllHighlights() {
    this.clearEditorHighlights();
    this.detectionResults = [];
    if (this.view) {
      this.view.setResults([]);
    }
    new import_obsidian5.Notice("已清除编辑器高亮");
  }
  getEditor() {
    const mdView = this.getMarkdownView();
    return (mdView == null ? void 0 : mdView.editor) || null;
  }
  getResults() {
    return this.detectionResults;
  }
  getOriginalText() {
    return this.originalText;
  }
};
